config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bartenders, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index] do
    resources :reviews, only: :create
  end
  patch "/accept", to: "bookings#accept", as: :accept
  patch "/reject", to: "bookings#reject", as: :reject
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bartender.rb
class Bartender < ApplicationRecord
  belongs_to :user

  has_one_attached :photo
  has_many :bookings
  has_many :reviews, through: :bookings

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bartender
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bartenders
  has_many :bookings
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bartenders_controller.rb
class BartendersController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        bartenders.city @@ :query \
        OR bartenders.description @@ :query \
        OR users.first_name @@ :query \
        OR users.last_name @@ :query \
      "
      @bartenders = Bartender.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @bartenders = Bartender.all
    end

    @markers = @bartenders.geocoded.map do |bartender|
      {
        lat: bartender.latitude,
        lng: bartender.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bartender: bartender })
      }
    end
  end

  def show
    @bartender = Bartender.find(params[:id])
  end

  def new
    @bartender = Bartender.new
  end

  def create
    @bartender = Bartender.new(bartender_params)
    @bartender.user = current_user
    if @bartender.save
      redirect_to bartender_path(@bartender)
    else
      render :new
    end
  end

  private

  def bartender_params
  params.require(:bartender).permit(:city, :description, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    # @bookings = Booking.all
    @review = Review.new
    @host = current_user.bartenders.any?
    @bookings = current_user.bookings
    if @host
      @my_requests = current_user.bartenders
      @my_bookings = Booking.where(bartender_id: @my_requests.pluck(:id))
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
  end

  def new
    @booking = Booking.new
    @bartender = Bartender.find(params[:bartender_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @bartender = Bartender.find(params[:bartender_id])
    @booking.user = current_user
    @booking.bartender = @bartender
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.status = "accepted"
    @booking.save
    redirect_to bookings_path(anchor: "booking-#{@booking.id}")
  end

  def reject
    @booking = Booking.find(params[:booking_id])
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path(anchor: "booking-#{@booking.id}")
  end

  private

  def booking_params
  params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @bartender = @booking.bartender
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to bartender_path(@bartender)
    else
      render 'bookings/index'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bartenders/_info_window.html.erb
<p><%= bartender.user.first_name %></p>
<%= link_to "Take a look", bartender_path(bartender.id), class:"btn btn-primary" %>

app/views/bartenders/index.html.erb
<div class="row justify-content-center">
</div>
  <div id="map"
    style="width: 100%; height: 370px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<div class="container mt-5">
  <div class="cards">
    <% @bartenders.each do |bartender| %>
      <div class="card shadow-lg border-0">
        <div class="card-body p-0">
            <% if bartender.photo.attached? %>
              <%= cl_image_tag bartender.photo.key, class:"w-100 card-img-top" %>
            <% else %>
                <%= image_tag "bartender_show.jpg" , :alt => "Close picture of bottles", class:"w-100 card-img-top "%>
            <% end %>
          <div class="p-4">
            <h5 class="mb-0"><%= bartender.user.first_name %></h5>
            <p class="small text-muted"><%= bartender.city %></p>
            <%= link_to "Take a look", bartender_path(bartender.id), class:"btn button-80" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bartenders/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center mt-3 pt-5">
    <div class="col">
      <div class="booking-card p-5">
        <h1>Create your <strong>bartender</strong> profile below!</h1>
        <%= simple_form_for(@bartender) do |f| %>
          <%= f.input :city %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <div class="form-actions">
            <%= f.button :submit, "Create profile", class:"btn btn-primary w-100 btn-bartender py-3 w-100" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bartenders/show.html.erb
<div class="container">
  <div id="bartenders-show">
    <div class="row justify-content-center">
      <div class="card-trip">

        <% if @bartender.photo.attached? %>
          <%= cl_image_tag @bartender.photo.key %>
        <% else %>
          <%= image_tag 'bartender_show.jpg' %>
        <% end %>

        <div class="card-trip-infos">
          <div>
            <h2><%= @bartender.user.first_name %></h2>
            <%= @bartender.city %>
          </div>
          <h2 class="card-trip-pricing"><%= link_to "Book now!", new_bartender_booking_path(@bartender), class:"mt-1 col btn btn-dark-moon btn-rounded"%></h2>
            <% if @bartender.user.photo.attached? %>
            <%= cl_image_tag @bartender.user.photo.key, class:"card-trip-user avatar-bordered" %>
            <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
            <% end %>
        </div>
      </div>
    </div>
    <div class="bartender-card-august">
      <div>
        <div class="card-product">
          <%= image_tag 'drink.jpg' %>
          <div class="card-product-infos">
            <h2>Pina colada</h2>
            <p>Product description with <strong>relevant info</strong> only.</p>
          </div>
        </div>
        <div class="card-product">
          <%= image_tag 'drink.jpg' %>
          <div class="card-product-infos">
            <h2>Crazy russian</h2>
            <p>Product description with <strong>relevant info</strong> only.</p>
          </div>
        </div>

      </div>
      <div class="card-august">
        <h3>Description</h3>
        <p><%= @bartender.description %></p>
      </div>
    </div>
    <div class="card-review">
      <h2>Reviews</h2>
        <% @bartender.reviews.each do |review| %>
          <p><%= review.content %></p>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="headers">
  <h1>My <strong>bookings</strong></h1>
</div>

<div class="container mt-5 justify-content-center">
  <div class="booking-card">
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card">
            <% if booking.bartender.photo.attached? %>
                    <%= cl_image_tag booking.bartender.photo.key, class:"card-img-top"  %>
                  <% else %>
                    <%= image_tag "bar_image.jpg" , :alt => "Close picture of bottles", class:"card-img-top"%>
                  <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= booking.bartender.user.first_name %></p></h5>
            <p class="card-text">Starts on <%= booking.start_date %></p>
            <p class="card-text">Until <%= booking.end_date %></p>
            <% if booking.status == "accepted" %>
            <span class="badge badge-success"><%= booking.status %></span>
            <% else %>
            <span class="badge badge-secondary"><%= booking.status %></span>
            <% end %>
            <% if booking.status == "accepted" %>
              <%= simple_form_for([ booking, @review ]) do |f| %>
                <p> Leave a review :</p>
                <%= f.input :content, as: :text, label: false %>
                <%= f.submit "Send review", class:"btn btn-bartender btn-dark-moon w-100" %>
              <% end %>
            <% end %>
      </div>
        </div>
      <% end %>
    </div>
</div>
  <div class="headers">
    <h1 class=mt-4>My <strong>booking</strong> requests</h1>
  </div>
<div class="container">
  <div class="booking-card">
    <div class="cards">
      <% if @my_bookings %>
      <% @my_bookings.each do |request| %>
        <div class="card" id="booking-<%= request.id %>">
          <%= image_tag "bar_image.jpg", :alt => "Bartender", class:"card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= request.bartender.user.first_name %></p></h5>
            <p class="card-text">Start: <%= request.start_date %></p>
            <p class="card-text">Until: <%= request.end_date %></p>
            <p class="card-text">Booked by: <%= request.user.first_name + " " + request.user.last_name %></p>
            <p class="card-text">Status: <%= request.status %></p>
            <%= link_to "Accept", accept_path(booking_id: request.id), method: :patch, class:"btn btn-success", remote: true%>
            <%= link_to "Reject", reject_path(booking_id: request.id), method: :patch, class:"btn btn-info"%>
          </div>
        </div>
        <% end %>
      <% else %>
      No bookings yet
      <% end %>
    </div>
  </div>
  </div>
</div>
  <%= link_to "Back to all Bartenders", bartenders_path, class: "btn btn-primary w-20 btn-bartender py-" %>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center mt-3 pt-5">
    <div class="col">
      <div class="booking-card p-5">
        <h1>Create a new book!</h1>
          <%= simple_form_for [@bartender, @booking] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <div class="form-actions">
              <%= f.button :submit, "Create booking", class:"btn btn-primary w-100 btn-bartender py-3" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentABartender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="main-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>

</html>

app/views/pages/home.html.erb
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag "bar_image.jpg" , :alt => "Close picture of bottles", class:"d-block w-100 banner-image"%>
          <div class="carousel-caption">

              <div class="m-5"><a href="/bartenders">Show <strong>bartenders</strong></a></div>

                <div class="row justify-content-center">
                  <div class="column col-4">
                      <%= form_tag bartenders_path, class:"form-inline search-bar", method: :get do %>
                        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Search by city"
                        %>
                        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
                      <% end %>
                  </div>
                </div>

          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag "bartender.jpg", class:"d-block w-100 banner-image", :alt => "Picture of a bartender in action" %>
          <div class="carousel-caption">

            <div class="m-5"><a href="/bartenders">Show <strong>bartenders</strong></a></div>

                <div class="row justify-content-center">
                  <div class="column col-4">
                      <%= form_tag bartenders_path, class:"form-inline search-bar", method: :get do %>
                        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Find a Bartender"
                        %>
                        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
                      <% end %>
                  </div>
                </div>


          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag "bottles.jpg", class:"d-block w-100 banner-image", :alt => "picture of bar with no people" %>
          <div class="carousel-caption">

              <div class="m-5"><a href="/bartenders">Show <strong>bartenders</strong></a></div>

                <div class="row justify-content-center">
                  <div class="column col-4">
                      <%= form_tag bartenders_path, class:"form-inline search-bar", method: :get do %>
                        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Find a Bartender"
                        %>
                        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
                      <% end %>
                  </div>
                </div>


          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag "shadows-of-bottles.jpg", class:"d-block w-100 banner-image", :alt => "picture of bar with no people" %>
          <div class="carousel-caption">

            <div class="m-5"><a href="/bartenders">Show <strong>bartenders</strong></a></div>

                <div class="row justify-content-center">
                  <div class="column col-4">
                      <%= form_tag bartenders_path, class:"form-inline search-bar", method: :get do %>
                        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Find a Bartender"
                        %>
                        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
                      <% end %>
                  </div>
                </div>


          </div>
        </div>
      </div>
  </div>
  
<div class="headers-homepage">
   <h1>Top rated <strong>bartenders</strong></h1>
</div>
<div class="row mt-10 justify-content-center">
</div>
  <div class="container mt-5">
  <div class="row pb-5 mb-4">
      <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
        <!-- Card-->
        <div class="card-home shadow-sm border-0">
          <div class="card-body p-0"><%= image_tag "person1.jpg", class:"w-100 card-img-top" %>
            <div class="p-4">
              <h5 class="mb-0">Elis liljeström</h5>
              <p class="small text-muted">Bartender</p>
              <ul class="social mb-0 list-inline mt-3">
                <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
      <!-- Card-->
      <div class="card-home shadow-sm border-0">
        <div class="card-body p-0"><%= image_tag "person2.jpg", class:"w-100 card-img-top" %>
          <div class="p-4">
            <h5 class="mb-0">Tom dracke</h5>
            <p class="small text-muted">Bartender</p>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
      <!-- Card-->
      <div class="card-home shadow-sm border-0">
        <div class="card-body p-0"><%= image_tag "person3.jpg", class:"w-100 card-img-top" %>
          <div class="p-4">
            <h5 class="mb-0">Freddie Mosten</h5>
            <p class="small text-muted">Bartender</p>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
      <!-- Card-->
      <div class="card-home shadow-sm border-0">
        <div class="card-body p-0"><%= image_tag "person4.jpg", class:"w-100 card-img-top" %>
          <div class="p-4">
            <h5 class="mb-0">Hanna Eklund</h5>
            <p class="small text-muted">Bartender</p>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item m-0"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
    <div class="social"><a href="#"><i class="fab fa-instagram"></i></a><a href="#"><i class="fab fa-facebook-f"></i></a><a href="#"><i class="fab fa-twitter"></i></a><a href="#"><i class="fab fa-linkedin"></i></a></div>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-glass-martini-alt" id="icon-navbar">Rent a bartender</i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mt-1">
          <%= link_to "Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <button type="button" class="btn-bartender btn-bartender-home">
            <%= link_to "Become a bartender", new_bartender_path, class: "nav-link" %>
          </button>
        </li>
        <li class="nav-item dropdown mt-1 ml-1">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/AugustWanger", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "Settings", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <button type="button" class="btn btn-login">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </button>
        </li>
      <% end %>
    </ul>
  </div>
</div>